services:
  api:
    image: alpine:3.20
    container_name: pragmatism-api
    working_dir: /app
    # NOTE: Ensure the binary below is a Linux build (e.g., GOOS=linux GOARCH=amd64)
    volumes:
      - ./Server/bin/PragmatismApp:/app/PragmatismApp:ro
      - ./Server/public:/app/public:ro
    # Ensure executable bit and run (helps if built on Windows)
    command: ["/bin/sh", "-c", "chmod +x /app/PragmatismApp && /app/PragmatismApp"]
    expose:
      - "3000"
    restart: unless-stopped

  nginx:
    image: nginx:1.25-alpine
    container_name: pragmatism-nginx
    depends_on:
      - api
    ports:
      - "8080:80"
      # If you have valid TLS certs mounted, you can also expose HTTPS locally
      - "8443:443"
    volumes:
      # Built SPA output folder from Vite/React
      - ./Client/dist:/var/www/dist_pragmatism:ro
  # Nginx config (dev, no TLS). Overwrite default.conf to avoid duplicate servers.
      - ./ops/nginx/pragmatism_app_nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
      # Optionally mount certs if using a TLS-enabled config
      # - ./ops/certs:/etc/letsencrypt:ro
    restart: unless-stopped

networks:
  default:
    name: pragmatism-net
