services:
  api:
    image: ghcr.io/karthik-shenoy/projects-mono-repo/pragmatism-api:latest
    container_name: pragmatism-api
    ports:
      - "3000:3000"   # Host needs this for Nginx proxy_pass http://localhost:3000
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
    restart: unless-stopped

  client:
    image: ghcr.io/karthik-shenoy/projects-mono-repo/pragmatism-client:latest
    container_name: pragmatism-client
    depends_on:
      - api
    ports:
      - "8080:80"
    restart: unless-stopped

  db:
    image: ghcr.io/karthik-shenoy/projects-mono-repo/pragmatism-db:latest
    container_name: pragmatism-db
    ports:
      - "5432:5432"
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    ports:
      - "5000:3000"
    volumes:
      - ./ops/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=grafana-clickhouse-datasource

  clickhouse:
    image: clickhouse/clickhouse-server:24.8
    container_name: clickhouse
    ports:
      - "8123:8123" # HTTP
      - "9000:9000" # Native TCP
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    restart: unless-stopped

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ./ops/otel-collector-config.yaml:/etc/otel-collector-config.yaml
      - ./ops/otel-output:/tmp/otel-output
    ports:
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
    depends_on:
      - clickhouse

networks:
  default:
    name: pragmatism-net

volumes:
  clickhouse-data:
