apiVersion: 1

datasources:
  - name: ClickHouse-OTel
    type: grafana-clickhouse-datasource
    isDefault: false
    jsonData:
      host: clickhouse
      port: 9000
      protocol: native
      username: default
      tlsSkipVerify: false
      defaultDatabase: otel
      logs:
        otelEnabled: true
        otelVersion: v1
        defaultDatabase: otel
        defaultTable: otel_logs
      traces:
        otelEnabled: true
        otelVersion: v1
        defaultDatabase: otel
        defaultTable: otel_traces
