services:

  # jaeger:
  #   image: jaegertracing/all-in-one:1.52
  #   container_name: jaeger
  #   ports:
  #     - "16686:16686"  # Jaeger UI
  #   restart: unless-stopped

  # prometheus:
  #   image: prom/prometheus:latest
  #   container_name: prometheus
  #   ports:
  #     - "9090:9090"  # Prometheus UI
  #   volumes:
  #     - ./prometheus.yml:/etc/prometheus/prometheus.yml
  #   restart: unless-stopped

  grafana:
    image: grafana/grafana
    ports:
      - "5000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.6
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
      - ./otel-output:/var/lib/otel-output
    ports:
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP

