name: Deploy Vite React & Go Backend

on:
  push:
    branches:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VM_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VM_HOST }} >> ~/.ssh/known_hosts

      - name: Pull Latest Changes And switch to prgmatis_master branch
        run: |
          ssh ${{ secrets.VM_USER_NAME }}@${{ secrets.VM_HOST }} << 'EOF'
            cd ~/git_repos/ProjectsMonoRepo
            git pull origin main
            git fetch origin pragmatism_master
            git checkout pragmatism_master
          EOF

      - name: Copy Dist Files to Web Root
        run: |
          ssh ${{ secrets.VM_USER_NAME }}@${{ secrets.VM_HOST }} << 'EOF'
            sudo cp -r ~/git_repos/ProjectsMonoRepo/Pragmatism/Client/dist/* /var/www/dist_pragmatism
          EOF

      - name: Decode and Se
        run: |
          
      
      - name: Run Go Backend
        run: |
          ssh ${{ secrets.VM_USER_NAME }}@${{ secrets.VM_HOST }} << 'EOF'
            cp ~/git_repos/ProjectsMonoRepo/Pragmatism/Server/bin/PragmatismApp ~/hosted/Pragmatism
            cp -r ~/git_repos/ProjectsMonoRepo/Pragmatism/Server/public ~/hosted/Pragmatism
            cd ~/hosted/Pragmatism
            mkdir .temp
            
            echo "${{ secrets.SET_ENV_SCRIPT }}" | base64 --decode > deploy.sh
            chmod +x deploy.sh
            ./deploy.sh
            
            chmod +x PragmatismApp
            nohup ./PragmatismApp > nohup.out 2>&1 &
          EOF

      - name: Restart Nginx
        run: |
          ssh ${{ secrets.VM_USER_NAME }}@${{ secrets.VM_HOST }} << 'EOF'
            sudo systemctl restart nginx
          EOF

      - name: Deployment Complete
        run: echo "Deployment finished successfully!"
